### ISSUE TITLE
Crash after sending away when already set to away

### ISSUE THREAD

**Issue by gahujipo** [blacksun80/LoxBerry-Plugin-Comfoconnect#11]
Hi. 
I think this crashes when one is sending a second time the away command. In the log I see this. 

```
03.04.2023 15:28:05 TASK STARTED

ComfoConnect Log

15:28:05.540 INFO: LoxBerry Version 3.0.0.3 ( is_arch_x86_64.cfg is_hwmodel_x86_64_vm.cfg is_x64.cfg )

15:28:05.540 INFO: Comfoconnect Version 0.2

15:28:05.540 INFO: Loglevel: 3

Exception in thread Thread-1:
Traceback (most recent call last):
File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
self.run()
File "/usr/lib/python3.9/threading.py", line 892, in run
self._target(*self._args, **self._kwargs)
File "/usr/lib/python3/dist-packages/paho/mqtt/client.py", line 3452, in _thread_main
self.loop_forever(retry_first_connection=True)
File "/usr/lib/python3/dist-packages/paho/mqtt/client.py", line 1779, in loop_forever
rc = self.loop(timeout, max_packets)
File "/usr/lib/python3/dist-packages/paho/mqtt/client.py", line 1181, in loop
rc = self.loop_read(max_packets)
File "/usr/lib/python3/dist-packages/paho/mqtt/client.py", line 1572, in loop_read
rc = self._packet_read()
File "/usr/lib/python3/dist-packages/paho/mqtt/client.py", line 2310, in _packet_read
rc = self._packet_handle()
File "/usr/lib/python3/dist-packages/paho/mqtt/client.py", line 2936, in _packet_handle
return self._handle_publish()
File "/usr/lib/python3/dist-packages/paho/mqtt/client.py", line 3216, in _handle_publish
self._handle_on_message(message)
File "/usr/lib/python3/dist-packages/paho/mqtt/client.py", line 3444, in _handle_on_message
self.on_message(self, self._userdata, message)
File "/opt/loxberry/bin/plugins/comfoconnect/cfc.py", line 88, in on_message
comfoconnect.cmd_rmi_request(CMD_FAN_MODE_AWAY)
File "/opt/loxberry/bin/plugins/comfoconnect/pycomfoconnect/comfoconnect.py", line 610, in cmd_rmi_request
reply = self._command(
File "/opt/loxberry/bin/plugins/comfoconnect/pycomfoconnect/comfoconnect.py", line 251, in _command
reply = self._get_reply(confirm_type, use_queue=use_queue)
File "/opt/loxberry/bin/plugins/comfoconnect/pycomfoconnect/comfoconnect.py", line 317, in _get_reply
raise ValueError('Timeout waiting for response.')
ValueError: Timeout waiting for response.
```

I have no idea of python therefore I cannot send you a pull request. Let me know if you need additional information or logs on this. 

Thanks in advance.

**Comment by gahujipo** [comment]
PS.: Using v0.2 on LB3.0

**Comment by blacksun80** [comment]
Warum macht man sowas? Das Problem hatte dann auch schon die V0.1.

**Comment by gahujipo** [comment]
Away startet mit einem Timer von 1h. Um away länger aufrecht zu erhalten hätte ich es öfters geschickt. Gibt es ein Register um die Zeit von Away zu erhöhen? 

Reicht das Logfile von oben oder brauchst du mehr Infos?

**Comment by blacksun80** [comment]
Für Away? Da gibt es ja gar keine Zeitvorgabe. Entweder schickt man ans Topic FAN_MODE eine 0, dann geht die Lüftungsstufe in Away Mode oder ich schicke an das Topic FAN_MODE_AWAY eine 1, dann geht auch die Lüftungsstufe auf Away. Da ist nix mit Zeit. 

`    # execute matching command
    if topic == mqtt_topic + "FAN_MODE":
        if int(value) == 0:
            comfoconnect.cmd_rmi_request(CMD_FAN_MODE_AWAY)
            _LOGGER.info("Befehl FAN_MODE_AWAY an Lüftungsanlage gesendet")
        elif int(value) == 1:
            comfoconnect.cmd_rmi_request(CMD_FAN_MODE_LOW)
            _LOGGER.info("Befehl FAN_MODE_LOW an Lüftungsanlage gesendet")
        elif int(value) == 2:
            comfoconnect.cmd_rmi_request(CMD_FAN_MODE_MEDIUM)
            _LOGGER.info("Befehl FAN_MODE_MEDIUM an Lüftungsanlage gesendet")
        elif int(value) == 3:
            comfoconnect.cmd_rmi_request(CMD_FAN_MODE_HIGH)
            _LOGGER.info("Befehl FAN_MODE_HIGH an Lüftungsanlage gesendet")
        else:
            _LOGGER.error("FAN_MODE: Ungültiger Wert wurde vom MQTT Broker empfangen - gültige Werte 0, 1, 2, 3")
    elif topic == mqtt_topic + "FAN_MODE_AWAY":
        if int(value) == 1:
            comfoconnect.cmd_rmi_request(CMD_FAN_MODE_AWAY)  # Go to away mode
            _LOGGER.info("Befehl FAN_MODE_AWAY an Lüftungsanlage gesendet")
        else:
            _LOGGER.error("FAN_MODE_AWAY: Ungültiger Wert wurde vom MQTT Broker empfangen - gültige Wert 1")`

**Comment by gahujipo** [comment]
Grundsätzlich wird in der ComfoControl App für Away ein Timer gesetzt. Dabei gibt man nach dem Tippen auf "Away" eine Endzeit ein. Bspw. resultiert daraus folgendes: 
![grafik](https://user-images.githubusercontent.com/26710574/230793926-7274d854-4e96-4ccc-aada-cd11d20d7a38.png)


Bei beiden von dir genannten Topics starten jeweils einen Timer für Away von zwei Stunden: 

![grafik](https://user-images.githubusercontent.com/26710574/230794051-815fa8d0-0928-4569-8e8e-b21077695e66.png)


Aktuell sehe ich mit diesem Plugin keine Alternative, Away (ohne die App) zu verlängern, ohne das Topic erneut zu schicken. Letzteres endet dann in den o.g. Crash. Oder übersehe ich etwas?

**Comment by blacksun80** [comment]
Da startet kein Timer sondern bei manuellem ändern der Lüfterstufe bleibt die Lüfterstufe auf hier Away bis dein Zeitprogramm die Lüfterstufe überschreibt.

Wenn ich die Lüfterstufe auf Away stelle, wird von Automatik auf Manuell gestellt. Diese gilt dann bis 8 Uhr da hier dann mein Zeitprogramm die Lüfterstufe hoch stellt

[image0.png]

In Loxone kann ich jetzt nicht nochmal auf Away stellen, sondern als nächstes dann auf Stufe 1

[image1.png]

Jetzt ist der Modus Away 579 min aktiv, bis 8 Uhr morgens bis das Zeitprogramm aktiv wird. Hier geht dann die Betriebsart wieder auf Automatik.

[image2.png]

[image3.png]

Wenn dann müsstest du die Betriebsart auf manuell stellen und dann die Lüfterstufe Away wählen. Dann bleibt Away so lange wie du willst auf der gewünschten Lüfterstufe. Da spielt dann das Zeitprogramm keine Rolle mehr.

[image4.png]

[image5.png]

Gruß
Michael

Von meinem iPhone gesendet

Am 09.04.2023 um 22:04 schrieb gahujipo ***@***.***>:

﻿

Grundsätzlich wird in der ComfoControl App für Away ein Timer gesetzt. Dabei gibt man nach dem Tippen auf "Away" eine Endzeit ein. Bspw. resultiert daraus folgendes:
[grafik]<https://user-images.githubusercontent.com/26710574/230793926-7274d854-4e96-4ccc-aada-cd11d20d7a38.png>

Bei beiden von dir genannten Topics starten jeweils einen Timer für Away von zwei Stunden:

[grafik]<https://user-images.githubusercontent.com/26710574/230794051-815fa8d0-0928-4569-8e8e-b21077695e66.png>

Aktuell sehe ich mit diesem Plugin keine Alternative, Away (ohne die App) zu verlängern, ohne das Topic erneut zu schicken. Letzteres endet dann in den o.g. Crash. Oder übersehe ich etwas?

**Comment by blacksun80** [comment]
Die Funktion für „Away bis“ aus dem 1. Screenshot muss neu sein, die kann das Plugin noch nicht. Da müsste man erst wissen, wie man das Datum und Uhrzeit übermittelt.

Von meinem iPhone gesendet

Am 09.04.2023 um 22:04 schrieb gahujipo ***@***.***>:

﻿

Grundsätzlich wird in der ComfoControl App für Away ein Timer gesetzt. Dabei gibt man nach dem Tippen auf "Away" eine Endzeit ein. Bspw. resultiert daraus folgendes:
[grafik]<https://user-images.githubusercontent.com/26710574/230793926-7274d854-4e96-4ccc-aada-cd11d20d7a38.png>

Bei beiden von dir genannten Topics starten jeweils einen Timer für Away von zwei Stunden:

[grafik]<https://user-images.githubusercontent.com/26710574/230794051-815fa8d0-0928-4569-8e8e-b21077695e66.png>

Aktuell sehe ich mit diesem Plugin keine Alternative, Away (ohne die App) zu verlängern, ohne das Topic erneut zu schicken. Letzteres endet dann in den o.g. Crash. Oder übersehe ich etwas?

**Comment by blacksun80** [comment]
Lange hat es gedauert, aber jetzt gehts wie von dir gewünscht. 

AWAY_FOR in Sekunden befüllen, für 10 Tage z. B. 10 * 86400
AWAY_END, wenn auf 1 gesetzt, wird der zeitgesteuerte Away Modus vorzeitig beendet
AWAY_ACTIVE, 1 = zeitgesteuerte Awaymodus ist aktiviert.
AWAY_REMAINING in s wie lange er noch läuft

Ein paar Sekundenwerte zum Nachschlagen: 1 Tag = 86400, 7 Tage = 604800, 10 Tage = 864000, 14 Tage = 1209600.
Zwei Hinweise: AWAY_ACTIVE und AWAY_REMAINING werden alle 15 Sekunden abgeholt (die Anlage bietet dafür kein Push an), nach dem Schalten dauert die Rückmeldung also bis zu 15s. Und AWAY_REMAINING wird nur bei Änderung gesendet — im Ruhezustand steht dort dauerhaft 0.

Kannst gerne mal den aktuellen Master testen.
